nodeLinker: "pnp"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

packageExtensions:
  formik-mui@*:
    dependencies:
      tiny-warning: "*"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
